version: '3'

services:
  gen-service:
    build:
      context: ./gen-service
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - backend

  demo-service:
    build:
      context: ./demo-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge
