services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - ~/minio/audiocraft-demo:/data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data
    networks:
      - backend
  gen-service:
    build:
      context: ./gen-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  demo-service:
    build:
      context: ./demo-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge
