// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO user_account (email, hashword)
VALUES ($1, $2)
RETURNING id, email, hashword, created_at, updated_at
`

type CreateUserParams struct {
	Email    string
	Hashword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Hashword)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Hashword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAccount = `-- name: GetUserAccount :one
SELECT id, email, hashword, created_at, updated_at
FROM user_account
WHERE email = $1
`

func (q *Queries) GetUserAccount(ctx context.Context, email string) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserAccount, email)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Hashword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
