// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO user_account (email, hashword)
VALUES ($1, $2)
RETURNING id, email, hashword
`

type CreateUserParams struct {
	Email    string
	Hashword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (UserAccount, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Hashword)
	var i UserAccount
	err := row.Scan(&i.ID, &i.Email, &i.Hashword)
	return i, err
}

const getUserCredential = `-- name: GetUserCredential :one
SELECT hashword
FROM user_account
WHERE email = $1
`

func (q *Queries) GetUserCredential(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRow(ctx, getUserCredential, email)
	var hashword string
	err := row.Scan(&hashword)
	return hashword, err
}
